[versions]
kotlin = "2.4.20"
ksp = "2.3.12"
loom = "1.18.2"
fabric-loader = "0.19.5"
fabric-kotlin = "1.14.1+kotlin.2.4.20"
devauth = "1.2.2"
junit = "5.14.4"
moulconfig = "4.7.2"
hypixel-mod-api = "1.0.2"
hypixel-fabric = "1.0.2+build.1"
auto-service-ksp = "1.2.0"
auto-service-annotations = "1.1.1"

[libraries]
auto-service-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "auto-service-ksp" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "auto-service-annotations" }
hypixel-mod-api = { module = "net.hypixel:mod-api", version.ref = "hypixel-mod-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
