package github.businessdirt.eurybium.processors

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated

class BuildInfoProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        BuildInfoProcessor(environment.codeGenerator, environment.options.getValue("eurybium.version"))
}

/** Minimal working KSP example. Generates metadata, not Minecraft version branches. */
private class BuildInfoProcessor(
    private val codeGenerator: CodeGenerator,
    private val version: String,
) : SymbolProcessor {
    private var generated = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()
        require(version.matches(Regex("[A-Za-z0-9.+_-]+"))) { "Unsupported mod version: $version" }
        codeGenerator.createNewFile(
            Dependencies.ALL_FILES,
            "github.businessdirt.eurybium.generated",
            "BuildInfo",
        ).bufferedWriter().use {
            it.write(
                """
                package github.businessdirt.eurybium.generated

                // Generated by KSP. Edit mod_version in gradle.properties instead.
                object BuildInfo {
                    const val VERSION: String = "$version"
                }
                """.trimIndent()
            )
        }
        generated = true
        return emptyList()
    }
}
